DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, email, full_name, status) VALUES
('john.doe', 'john.doe@example.com', 'John Doe', 'ACTIVE');
INSERT INTO users (username, email, full_name, status) VALUES
('jane.smith', 'jane.smith@example.com', 'Jane Smith', 'ACTIVE');
INSERT INTO users (username, email, full_name, status) VALUES
('bob.wilson', 'bob.wilson@example.com', 'Bob Wilson', 'INACTIVE');
