DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Credentials table for authentication (separate from profile data)
DROP TABLE IF EXISTS user_credentials;
CREATE TABLE IF NOT EXISTS user_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    roles VARCHAR(255) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- Generic outbox table for reliable message publishing (future use)
DROP TABLE IF EXISTS message_outbox;
CREATE TABLE IF NOT EXISTS message_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    headers TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

INSERT INTO users (username, email, full_name, status) VALUES
('john.doe', 'john.doe@example.com', 'John Doe', 'ACTIVE');
INSERT INTO users (username, email, full_name, status) VALUES
('jane.smith', 'jane.smith@example.com', 'Jane Smith', 'ACTIVE');
INSERT INTO users (username, email, full_name, status) VALUES
('bob.wilson', 'bob.wilson@example.com', 'Bob Wilson', 'INACTIVE');

-- Seed credentials (password = 'password' BCrypt hash placeholder) ONLY for dev/local
INSERT INTO user_credentials (username, password_hash, roles) VALUES
 ('john.doe', '{bcrypt}$2a$10$K0d9vQYpQ7h7JkQ0Yp5x4O0ZpQWcO9J3uQmV0xZp7YfFJ5Yd8Qm8G', 'USER'),
 ('jane.smith', '{bcrypt}$2a$10$K0d9vQYpQ7h7JkQ0Yp5x4O0ZpQWcO9J3uQmV0xZp7YfFJ5Yd8Qm8G', 'USER,ADMIN');
